import { Montserrat } from "next/font/google";
import "./globals.css";
import BaseLayout from "@/layout/BaseLayout";

const montserrat = Montserrat({
  weight: ["400", "700", "900"],
  style: ["normal"],
  subsets: ["cyrillic"]
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <BaseLayout child={children}/>
      </body>
    </html>
  );
}
