import { Montserrat } from "next/font/google";
import "./globals.css";
import TopTitle from "@/components/shared/TopTitle";
import { Footer, Navbar } from "@/components";

const montserrat = Montserrat({
  weight: ["400", "700", "900"],
  style: ["normal"],
  subsets: ["cyrillic"]
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <TopTitle/>
        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
